# Generated by Django 5.2.3 on 2025-06-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={"verbose_name": "Candidate", "verbose_name_plural": "Candidates"},
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
