# Generated by Django 5.2.3 on 2025-06-16 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_candidate_options_alter_candidate_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="description",
        ),
        migrations.RemoveField(
            model_name="company",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="company",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="company",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="company",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="companyuser",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="companyuser",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="companyuser",
            name="linked_candidate",
        ),
        migrations.RemoveField(
            model_name="companyuser",
            name="manager",
        ),
        migrations.AddField(
            model_name="company",
            name="private_code",
            field=models.CharField(default=10, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("hr", "HR"), ("manager", "Manager")],
                max_length=20,
            ),
        ),
    ]
