# Generated by Django 5.2.3 on 2025-06-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_company_description_remove_company_industry_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="private_code",
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("hr", "HR"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                max_length=20,
            ),
        ),
    ]
