# Generated by Django 5.2.3 on 2025-06-19 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_jobrole_alter_application_job_delete_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyuser",
            name="created_at",
        ),
        migrations.AddField(
            model_name="companyuser",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="core.companyuser",
            ),
        ),
    ]
