# Generated by Django 5.2.3 on 2025-06-19 01:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_companyuser_created_at_companyuser_manager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyuser",
            old_name="manager",
            new_name="manager1",
        ),
    ]
