# Generated by Django 5.2.3 on 2025-06-19 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_manager_companyuser_manager1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyuser",
            old_name="manager1",
            new_name="manager",
        ),
    ]
