# Generated by Django 5.2.3 on 2025-06-19 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_rename_manager1_companyuser_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyuser",
            name="manager",
        ),
        migrations.AddField(
            model_name="companyuser",
            name="manager1",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="core.companyuser",
            ),
        ),
    ]
