# Generated by Django 5.2.3 on 2025-06-19 18:59

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_companyuser_manager_companyuser_manager1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyuser",
            old_name="manager1",
            new_name="manager",
        ),
        migrations.RemoveField(
            model_name="timesheet",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="timesheet",
            name="hours",
        ),
        migrations.RemoveField(
            model_name="timesheet",
            name="status",
        ),
        migrations.RemoveField(
            model_name="timesheet",
            name="submitted_on",
        ),
        migrations.AddField(
            model_name="timesheet",
            name="approved",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="earn_code",
            field=models.CharField(default="Regular", max_length=50),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="hours_worked",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("8.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="end_time",
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="start_time",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
