# Generated by Django 5.2.3 on 2025-06-19 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_rename_manager1_companyuser_manager_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timesheet",
            name="earn_code",
        ),
        migrations.RemoveField(
            model_name="timesheet",
            name="employee",
        ),
        migrations.AddField(
            model_name="timesheet",
            name="company_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timesheets",
                to="core.companyuser",
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="hours_worked",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
