# Generated by Django 5.2.3 on 2025-06-24 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_timesheet_earn_code_remove_timesheet_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.companyuser",
            ),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("hr", "HR"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                max_length=50,
            ),
        ),
    ]
