# Generated by Django 5.2.3 on 2025-06-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_companyuser_manager_alter_companyuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
