# Generated by Django 5.2.3 on 2025-06-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_resumesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="preferred_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
