# Generated by Django 5.2.3 on 2025-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_candidate_address_candidate_linkedin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="govt_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Government ID Number",
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="ssn",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
